### PR TITLE
Use COMPUTE_MAXS instead of COMPUTE_FRAMES to avoid wasting performance

### PR DESCRIPTION
**Pull request by Hippo**
In Transformer#emptyMethod the stack and local sizes are incorrectly computed, which may cause verification problems on some vms.

### CODE REVIEW

**Comment by Vladymyr** [comment]
First off, thanks for making a pull request trying to help, that's always appreciated. Your solution would be necessary if I had no flags for the ```ClassWriter```. However, I do use ```COMPUTE_FLAGS``` (see  [AntiAgentAgent#transform](https://github.com/Vladymyr/Anti-Agent-Agent/blob/master/src/main/java/xyz/vladymyr/agent/AntiAgentAgent.java#L268)) which official ASM documentation states:

> A flag to automatically compute the stack map frames of methods from scratch. If this flag is
> set, then the calls to the {@link MethodVisitor#visitFrame} method are ignored, and the stack
> map frames are recomputed from the method's bytecode. The arguments of the {@link
> MethodVisitor#visitMaxs} method are also ignored and recomputed from the bytecode. In other
> words, {@link #COMPUTE_FRAMES} implies {@link #COMPUTE_MAXS}.

As you can read above, it doesn't only compute the stack map frames, it also computes maximum stack size and the maximum number of local variables (implies ```COMPUTE_MAXS```). Meaning that calculating the sizes you mentioned would be redundant since they would get overwritten anyway. In case If you're wondering why I didn't use ```COMPUTE_MAXS``` directly instead, it's documentation has a note:

> <p><b>Note:</b> for classes whose version is {@link Opcodes#V1_7} of more, this option requires
> valid stack map frames. The maximum stack size is then computed from these frames, and from the
> bytecode instructions in between. If stack map frames are not present or must be recomputed,
> used {@link #COMPUTE_FRAMES} instead.

Because I want this project to be compatible with more versions than Java 1.7, it seemed like the best solution. Despite all of this,  I'm curious and would like to know how did you end up with the conclusion that it may cause verification problems on some VMS. Did you experience it first hand? Or was it just a simple deduction?

**Comment by Hippo** [comment]
You made some fairly good points, though personally I would look more into `COMPUTE_MAXS`, I believe it would work considering it doesn't need the stack map frames to compute the parameter size. But in that regard, I went in and removed setting the variables directly since they would be overridden by the `ClassWriter` anyway.

**Comment by Vladymyr** [comment]
I already was aware that ```COMPUTE_MAXS``` should be able to do the job, in principle, it should be possible to just use the original frames. Then it wouldn't be necessary to specify the ```COMPUTE_FRAMES``` flag to the ```ClassWriter``` (see [AntiAgentAgent#transform](https://github.com/Vladymyr/Anti-Agent-Agent/blob/master/src/main/java/xyz/vladymyr/agent/AntiAgentAgent.java#L268)), neither ```SKIP_FRAMES``` flag to the ```ClassReader``` (see [AntiAgentAgent#readClass](https://github.com/Vladymyr/Anti-Agent-Agent/blob/master/src/main/java/xyz/vladymyr/agent/AntiAgentAgent.java#L245)).

Each stack map frame is a position where types are either explicitly or implicitly (```this``` as first in virtual methods) listed. The preferable approach would calculate the stack map frames based on the original frames, according to the code modifications that were made (in our case, emptying it). There should be no frames in the method (control flow never joins), in consequence, the StackMapTable attribute can be omitted entirely. Meaning that technically we could avoid using ```COMPUTE_FRAMES``` wasting resources to find out the common base class in a deep class hierarchy tree (shouldn't matter since the impact on the performance is unnoticeable). My doubts come as I'm unsure if using ```COMPUTE_MAXS``` would give no problems whatsoever.

**Comment by Vladymyr** [comment]
Wanted also to mention since you didn't write any reason and/or example of why it could cause verification problems for some VMs, I'm assuming it was a simple deduction. I'm changing the title to something that should suit it better,

**Comment by Hippo** [comment]
With further testing the agent has no problems with `COMPUTE_MAXS`. With the cleared method there is no StackMapFrames present and ASM has no issues computing the stack and locals.

**Pull request merged**
